const reviewData = {
  products: [
    { id: "galaxy-s27-ultra", name: "Galaxy S27 Ultra", category: "Smartphones", portal: "GSMArena-style specs", image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=900", rating: 4.8, score: 9.7, reviews: 1284, trend: "+18%", price: "$1,199", verdict: "Best overall Android flagship for camera, display, and battery.", pros: ["Excellent zoom camera", "Bright display", "Long battery life"], specs: { Display: "6.9-inch AMOLED, 144Hz", Processor: "Snapdragon 8 Elite", Camera: "200MP + 50MP + 12MP", Battery: "5,500mAh", Storage: "256GB / 512GB / 1TB", Warranty: "1 year" } },
    { id: "iphone-18-pro-max", name: "iPhone 18 Pro Max", category: "Smartphones", portal: "Editorial review", image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900", rating: 4.7, score: 9.5, reviews: 1106, trend: "+14%", price: "$1,249", verdict: "Best choice for video, app ecosystem, and long software support.", pros: ["Superb video", "Fast chipset", "Strong resale value"], specs: { Display: "6.8-inch OLED, 120Hz", Processor: "A20 Pro", Camera: "48MP + 48MP + 12MP", Battery: "4,900mAh", Storage: "256GB / 512GB / 1TB", Warranty: "1 year" } },
    { id: "pixel-10-pro", name: "Pixel 10 Pro", category: "Smartphones", portal: "Camera ranking", image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=900", rating: 4.6, score: 9.2, reviews: 742, trend: "+21%", price: "$999", verdict: "Best computational photography and clean Android experience.", pros: ["Natural photos", "Helpful AI features", "Clean software"], specs: { Display: "6.7-inch OLED, 120Hz", Processor: "Tensor G6", Camera: "50MP + 48MP + 48MP", Battery: "5,050mAh", Storage: "128GB / 256GB / 512GB", Warranty: "1 year" } },
    { id: "macbook-air-m5", name: "MacBook Air M5", category: "Laptops", portal: "Wirecutter-style pick", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=900", rating: 4.6, score: 9.3, reviews: 892, trend: "+9%", price: "$1,099", verdict: "Best thin laptop for students, writers, and everyday professionals.", pros: ["Silent design", "Great battery", "Excellent trackpad"], specs: { Display: "13.6-inch Liquid Retina", Processor: "Apple M5", Camera: "1080p webcam", Battery: "18 hours rated", Storage: "256GB / 512GB / 1TB", Warranty: "1 year" } },
    { id: "rog-zephyrus-g16", name: "ROG Zephyrus G16", category: "Laptops", portal: "Gaming benchmark", image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=900", rating: 4.7, score: 9.4, reviews: 624, trend: "+16%", price: "$1,899", verdict: "Best portable gaming laptop with strong performance and a premium screen.", pros: ["Fast GPU", "OLED option", "Slim chassis"], specs: { Display: "16-inch OLED, 240Hz", Processor: "Intel Core Ultra 9", Camera: "1080p webcam", Battery: "90Wh", Storage: "1TB / 2TB", Warranty: "1 year" } },
    { id: "dell-xps-14", name: "Dell XPS 14", category: "Laptops", portal: "Business review", image: "https://images.unsplash.com/photo-1587554801471-37976a256db0?w=900", rating: 4.4, score: 8.8, reviews: 511, trend: "+6%", price: "$1,499", verdict: "Premium Windows laptop with polished build and strong everyday speed.", pros: ["Premium keyboard", "Sharp display", "Compact design"], specs: { Display: "14.5-inch OLED", Processor: "Intel Core Ultra 7", Camera: "1080p webcam", Battery: "69.5Wh", Storage: "512GB / 1TB / 2TB", Warranty: "1 year" } },
    { id: "sony-wh-1000xm7", name: "Sony WH-1000XM7", category: "Audio", portal: "Audio lab", image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900", rating: 4.8, score: 9.4, reviews: 1532, trend: "+23%", price: "$399", verdict: "Best noise-canceling headphones for travel and office focus.", pros: ["Class-leading ANC", "Comfortable fit", "Long battery"], specs: { Display: "N/A", Processor: "QN3 audio processor", Camera: "N/A", Battery: "34 hours rated", Storage: "N/A", Warranty: "1 year" } },
    { id: "airpods-pro-3", name: "AirPods Pro 3", category: "Audio", portal: "Buyer ratings", image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=900", rating: 4.5, score: 8.9, reviews: 1203, trend: "+11%", price: "$249", verdict: "Best earbuds for iPhone users who want easy pairing and compact ANC.", pros: ["Great iOS integration", "Small case", "Clear calls"], specs: { Display: "N/A", Processor: "H3 audio chip", Camera: "N/A", Battery: "7 hours buds / 30 hours case", Storage: "N/A", Warranty: "1 year" } },
    { id: "apple-watch-ultra-3", name: "Apple Watch Ultra 3", category: "Wearables", portal: "Fitness tracker lab", image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=900", rating: 4.5, score: 9.0, reviews: 687, trend: "+8%", price: "$799", verdict: "Best rugged smartwatch for iPhone users and endurance tracking.", pros: ["Tough build", "Accurate GPS", "Bright screen"], specs: { Display: "49mm LTPO OLED", Processor: "S11", Camera: "N/A", Battery: "Up to 72 hours low power", Storage: "64GB", Warranty: "1 year" } },
    { id: "samsung-galaxy-watch-9", name: "Samsung Galaxy Watch 9", category: "Wearables", portal: "Android wearable review", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900", rating: 4.4, score: 8.8, reviews: 721, trend: "+12%", price: "$349", verdict: "Best Android smartwatch for health tracking and daily notifications.", pros: ["Good health sensors", "Comfortable band", "Nice display"], specs: { Display: "1.5-inch AMOLED", Processor: "Exynos W-series", Camera: "N/A", Battery: "Up to 48 hours", Storage: "32GB", Warranty: "1 year" } },
    { id: "nike-air-max-2026", name: "Nike Air Max 2026", category: "Lifestyle", portal: "Buyer comfort log", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900", rating: 4.3, score: 8.6, reviews: 433, trend: "+19%", price: "$169", verdict: "Stylish everyday sneaker with strong cushioning for city walking.", pros: ["Comfortable sole", "Bold colors", "Easy styling"], specs: { Display: "N/A", Processor: "N/A", Camera: "N/A", Battery: "N/A", Storage: "N/A", Warranty: "30-day return window" } },
    { id: "dyson-v16-detect", name: "Dyson V16 Detect", category: "Home", portal: "Home appliance lab", image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=900", rating: 4.4, score: 8.9, reviews: 362, trend: "+7%", price: "$749", verdict: "Powerful cordless vacuum for hard floors, pet hair, and quick cleaning.", pros: ["Strong suction", "Useful dust light", "Good attachments"], specs: { Display: "LCD status screen", Processor: "Dust detect sensor", Camera: "N/A", Battery: "70 minutes rated", Storage: "N/A", Warranty: "2 years" } }
  ],
  reviews: [
    { productId: "galaxy-s27-ultra", author: "Mia R.", type: "Verified buyer", rating: 5, date: "2026-06-05T18:42:00+08:00", title: "Camera zoom is the real upgrade", text: "Low-light photos and long-range zoom are both better than my last phone. It is heavy, but the battery easily lasts my workday." },
    { productId: "iphone-18-pro-max", author: "Carlos D.", type: "Verified buyer", rating: 5, date: "2026-06-04T09:15:00+08:00", title: "Excellent video and smooth apps", text: "The video quality is why I bought it. Charging speed is still my only complaint." },
    { productId: "macbook-air-m5", author: "Janelle P.", type: "Verified buyer", rating: 4, date: "2026-06-03T21:04:00+08:00", title: "Great school laptop", text: "Silent, light, and fast enough for research, documents, and light editing. I wish the base model had more storage." },
    { productId: "sony-wh-1000xm7", author: "Noah S.", type: "Verified buyer", rating: 5, date: "2026-06-02T14:30:00+08:00", title: "Noise canceling is excellent", text: "Very comfortable during flights and the app gives enough EQ control for my taste." },
    { productId: "rog-zephyrus-g16", author: "Ken T.", type: "Verified buyer", rating: 4, date: "2026-05-31T20:17:00+08:00", title: "Fast gaming laptop, loud fans", text: "Frame rates are excellent and the OLED screen looks amazing. Fan noise is noticeable when performance mode is on." },
    { productId: "dyson-v16-detect", author: "Alyssa B.", type: "Verified buyer", rating: 4, date: "2026-05-29T10:48:00+08:00", title: "Great for pets", text: "It picks up pet hair quickly. The bin fills fast, but cleaning performance is strong." }
  ],
  articles: [
    { title: "Best Smartphones of 2026", category: "Smartphones", date: "2026-06-06T08:00:00+08:00", source: "ReviewHub Editorial", summary: "A ranked guide to the strongest phones for camera quality, battery life, gaming, and value." },
    { title: "Best Laptops Under $1000", category: "Laptops", date: "2026-06-04T11:30:00+08:00", source: "ReviewHub Buying Guide", summary: "Affordable laptop picks for students, office work, and hybrid productivity." },
    { title: "Noise-Canceling Headphones Compared", category: "Audio", date: "2026-06-02T16:20:00+08:00", source: "Audio Lab Notes", summary: "We compare ANC strength, comfort, microphone quality, and battery life across leading headphones." },
    { title: "Smartwatch Health Tracking: What Matters", category: "Wearables", date: "2026-05-30T13:00:00+08:00", source: "Fitness Tracker Desk", summary: "A practical look at GPS, sleep tracking, heart-rate accuracy, and platform compatibility." }
  ]
};

reviewData.products.push(
  { id: "iphone-15-pro-max", name: "iPhone 15 Pro Max", category: "Smartphones", portal: "Phone specs", image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=900", rating: 4.7, score: 9.2, reviews: 4892, trend: "+10%", price: "$1,199", verdict: "Premium iPhone with strong cameras, titanium build, and excellent video.", pros: ["Great video", "Fast performance", "Premium build"], specs: { Display: "6.7-inch OLED, 120Hz", Processor: "A17 Pro", Camera: "48MP + 12MP + 12MP", Battery: "Up to 29 hours video", Storage: "256GB / 512GB / 1TB", Warranty: "1 year" } },
  { id: "iphone-15", name: "iPhone 15", category: "Smartphones", portal: "Buyer ratings", image: "https://images.unsplash.com/photo-1695048132832-b41495f12eb4?w=900", rating: 4.5, score: 8.8, reviews: 4021, trend: "+7%", price: "$799", verdict: "Balanced iPhone for everyday users who want reliable cameras and long support.", pros: ["Reliable camera", "USB-C", "Smooth software"], specs: { Display: "6.1-inch OLED", Processor: "A16 Bionic", Camera: "48MP + 12MP", Battery: "All-day battery", Storage: "128GB / 256GB / 512GB", Warranty: "1 year" } },
  { id: "galaxy-s24-ultra", name: "Samsung Galaxy S24 Ultra", category: "Smartphones", portal: "Phone specs", image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=900", rating: 4.7, score: 9.3, reviews: 5120, trend: "+12%", price: "$1,299", verdict: "A powerful Android flagship with stylus support and excellent zoom.", pros: ["S Pen", "Sharp display", "Strong zoom"], specs: { Display: "6.8-inch AMOLED, 120Hz", Processor: "Snapdragon 8 Gen 3", Camera: "200MP quad camera", Battery: "5,000mAh", Storage: "256GB / 512GB / 1TB", Warranty: "1 year" } },
  { id: "galaxy-a55", name: "Samsung Galaxy A55", category: "Smartphones", portal: "Value ranking", image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=900", rating: 4.3, score: 8.5, reviews: 2780, trend: "+13%", price: "$449", verdict: "Good midrange phone with solid display, battery, and everyday performance.", pros: ["Good value", "Bright screen", "Reliable battery"], specs: { Display: "6.6-inch AMOLED, 120Hz", Processor: "Exynos midrange", Camera: "50MP triple camera", Battery: "5,000mAh", Storage: "128GB / 256GB", Warranty: "1 year" } },
  { id: "pixel-8-pro", name: "Google Pixel 8 Pro", category: "Smartphones", portal: "Camera review", image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=900", rating: 4.5, score: 9.0, reviews: 3102, trend: "+9%", price: "$999", verdict: "Excellent Android camera phone with clean software and smart editing tools.", pros: ["Great photos", "Clean Android", "Helpful AI"], specs: { Display: "6.7-inch OLED, 120Hz", Processor: "Tensor G3", Camera: "50MP + 48MP + 48MP", Battery: "5,050mAh", Storage: "128GB / 256GB / 512GB", Warranty: "1 year" } },
  { id: "oneplus-12", name: "OnePlus 12", category: "Smartphones", portal: "Performance review", image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=900", rating: 4.6, score: 9.1, reviews: 2210, trend: "+15%", price: "$799", verdict: "Fast flagship with excellent charging and a polished display.", pros: ["Very fast charging", "Smooth display", "Strong value"], specs: { Display: "6.8-inch AMOLED, 120Hz", Processor: "Snapdragon 8 Gen 3", Camera: "50MP + 64MP + 48MP", Battery: "5,400mAh", Storage: "256GB / 512GB", Warranty: "1 year" } },
  { id: "xiaomi-14-ultra", name: "Xiaomi 14 Ultra", category: "Smartphones", portal: "Camera ranking", image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=900", rating: 4.6, score: 9.2, reviews: 1604, trend: "+17%", price: "$1,099", verdict: "Camera-focused flagship with versatile lenses and premium hardware.", pros: ["Excellent lenses", "Fast charging", "Premium screen"], specs: { Display: "6.73-inch AMOLED, 120Hz", Processor: "Snapdragon 8 Gen 3", Camera: "50MP quad camera", Battery: "5,000mAh", Storage: "256GB / 512GB / 1TB", Warranty: "1 year" } },
  { id: "oppo-find-x7-ultra", name: "OPPO Find X7 Ultra", category: "Smartphones", portal: "Camera review", image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=900", rating: 4.5, score: 9.0, reviews: 1188, trend: "+11%", price: "$999", verdict: "Premium Android phone with strong portrait and zoom camera performance.", pros: ["Portrait photos", "Zoom quality", "Fast charging"], specs: { Display: "6.82-inch AMOLED, 120Hz", Processor: "Snapdragon 8 Gen 3", Camera: "50MP quad camera", Battery: "5,000mAh", Storage: "256GB / 512GB", Warranty: "1 year" } },
  { id: "vivo-x100-pro", name: "vivo X100 Pro", category: "Smartphones", portal: "Camera lab", image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=900", rating: 4.5, score: 8.9, reviews: 1212, trend: "+8%", price: "$899", verdict: "Strong camera phone for portraits, zoom, and night photography.", pros: ["Night photos", "Portrait lens", "Fast charging"], specs: { Display: "6.78-inch AMOLED, 120Hz", Processor: "Dimensity 9300", Camera: "50MP triple camera", Battery: "5,400mAh", Storage: "256GB / 512GB", Warranty: "1 year" } },
  { id: "nothing-phone-2", name: "Nothing Phone 2", category: "Smartphones", portal: "Design review", image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=900", rating: 4.2, score: 8.4, reviews: 1440, trend: "+6%", price: "$599", verdict: "Distinctive Android phone with a clean interface and eye-catching rear lights.", pros: ["Unique design", "Clean UI", "Good screen"], specs: { Display: "6.7-inch OLED, 120Hz", Processor: "Snapdragon 8+ Gen 1", Camera: "50MP dual camera", Battery: "4,700mAh", Storage: "128GB / 256GB / 512GB", Warranty: "1 year" } },
  { id: "honor-magic6-pro", name: "Honor Magic6 Pro", category: "Smartphones", portal: "Flagship ranking", image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=900", rating: 4.5, score: 8.9, reviews: 934, trend: "+10%", price: "$1,099", verdict: "Premium Android flagship with a bright display and strong battery life.", pros: ["Bright screen", "Big battery", "Fast performance"], specs: { Display: "6.8-inch OLED, 120Hz", Processor: "Snapdragon 8 Gen 3", Camera: "50MP triple camera", Battery: "5,600mAh", Storage: "256GB / 512GB", Warranty: "1 year" } },
  { id: "motorola-edge-50-pro", name: "Motorola Edge 50 Pro", category: "Smartphones", portal: "Midrange review", image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=900", rating: 4.2, score: 8.3, reviews: 812, trend: "+5%", price: "$549", verdict: "Slim Android phone with fast charging and a clean software feel.", pros: ["Slim design", "Fast charging", "Clean Android"], specs: { Display: "6.7-inch pOLED, 144Hz", Processor: "Snapdragon 7 series", Camera: "50MP triple camera", Battery: "4,500mAh", Storage: "256GB", Warranty: "1 year" } },
  { id: "garmin-fenix-8", name: "Garmin Fenix 8", category: "Wearables", portal: "Fitness tracker lab", image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=900", rating: 4.8, score: 9.5, reviews: 1652, trend: "+14%", price: "$899", verdict: "Rugged multisport watch for serious training, hiking, and battery life.", pros: ["Long battery", "Accurate GPS", "Deep metrics"], specs: { Display: "AMOLED or MIP options", Processor: "Garmin sensor platform", Camera: "N/A", Battery: "Multi-day battery", Storage: "Maps and music", Warranty: "1 year" } },
  { id: "fitbit-sense-3", name: "Fitbit Sense 3", category: "Wearables", portal: "Health review", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900", rating: 4.2, score: 8.4, reviews: 1833, trend: "+6%", price: "$299", verdict: "Health-first smartwatch with approachable wellness tracking.", pros: ["Sleep tracking", "Lightweight", "Simple app"], specs: { Display: "AMOLED", Processor: "Fitbit health platform", Camera: "N/A", Battery: "Up to 6 days", Storage: "N/A", Warranty: "1 year" } },
  { id: "huawei-watch-gt-5", name: "Huawei Watch GT 5", category: "Wearables", portal: "Wearable review", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900", rating: 4.3, score: 8.6, reviews: 910, trend: "+7%", price: "$329", verdict: "Stylish smartwatch with long battery life and fitness tracking.", pros: ["Long battery", "Premium look", "Good fitness modes"], specs: { Display: "AMOLED", Processor: "Huawei wearable platform", Camera: "N/A", Battery: "Up to 14 days", Storage: "N/A", Warranty: "1 year" } },
  { id: "ipad-pro-m4", name: "iPad Pro M4", category: "Tablets", portal: "Tablet review", image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=900", rating: 4.7, score: 9.3, reviews: 2219, trend: "+18%", price: "$999", verdict: "Ultra-thin tablet with an excellent display and laptop-class power.", pros: ["Excellent OLED", "Fast chip", "Thin design"], specs: { Display: "11 or 13-inch OLED", Processor: "Apple M4", Camera: "12MP", Battery: "All-day battery", Storage: "256GB to 2TB", Warranty: "1 year" } },
  { id: "galaxy-tab-s9-ultra", name: "Galaxy Tab S9 Ultra", category: "Tablets", portal: "Tablet specs", image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=900", rating: 4.5, score: 9.0, reviews: 1403, trend: "+9%", price: "$1,199", verdict: "Huge Android tablet with S Pen support and a vivid AMOLED screen.", pros: ["Large screen", "S Pen included", "Water resistant"], specs: { Display: "14.6-inch AMOLED, 120Hz", Processor: "Snapdragon 8 Gen 2", Camera: "Dual rear camera", Battery: "11,200mAh", Storage: "256GB / 512GB / 1TB", Warranty: "1 year" } },
  { id: "kindle-paperwhite", name: "Kindle Paperwhite", category: "Gadgets", portal: "Reader review", image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=900", rating: 4.6, score: 9.0, reviews: 8301, trend: "+5%", price: "$149", verdict: "Best simple e-reader for books, travel, and glare-free reading.", pros: ["Water resistant", "Long battery", "Sharp text"], specs: { Display: "6.8-inch e-ink", Processor: "E-reader platform", Camera: "N/A", Battery: "Weeks", Storage: "8GB / 16GB", Warranty: "1 year" } },
  { id: "sony-ps5-slim", name: "Sony PlayStation 5 Slim", category: "Gaming", portal: "Gaming review", image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=900", rating: 4.7, score: 9.1, reviews: 6204, trend: "+13%", price: "$499", verdict: "Powerful console with a strong game library and fast loading.", pros: ["Fast SSD", "Great exclusives", "Strong controller"], specs: { Display: "4K output", Processor: "AMD custom CPU/GPU", Camera: "N/A", Battery: "N/A", Storage: "1TB SSD", Warranty: "1 year" } },
  { id: "nintendo-switch-oled", name: "Nintendo Switch OLED", category: "Gaming", portal: "Gaming review", image: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=900", rating: 4.6, score: 8.9, reviews: 7205, trend: "+8%", price: "$349", verdict: "Portable console with a vibrant screen and family-friendly games.", pros: ["Portable", "Great OLED", "Huge library"], specs: { Display: "7-inch OLED", Processor: "NVIDIA Tegra", Camera: "N/A", Battery: "4.5 to 9 hours", Storage: "64GB", Warranty: "1 year" } },
  { id: "lg-c4-oled-tv", name: "LG C4 OLED TV", category: "Appliances", portal: "TV lab", image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=900", rating: 4.7, score: 9.3, reviews: 2410, trend: "+12%", price: "$1,499", verdict: "Excellent OLED TV for movies, sports, and gaming.", pros: ["Deep blacks", "Low latency", "Great HDR"], specs: { Display: "OLED, 120Hz", Processor: "Alpha image processor", Camera: "N/A", Battery: "N/A", Storage: "N/A", Warranty: "1 year" } },
  { id: "samsung-frame-tv", name: "Samsung The Frame TV", category: "Appliances", portal: "Home entertainment", image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=900", rating: 4.4, score: 8.7, reviews: 1988, trend: "+9%", price: "$1,299", verdict: "Stylish TV that doubles as wall art when not in use.", pros: ["Art mode", "Matte display", "Clean mounting"], specs: { Display: "QLED matte display", Processor: "Samsung image processor", Camera: "N/A", Battery: "N/A", Storage: "N/A", Warranty: "1 year" } },
  { id: "lg-washer-dryer-combo", name: "LG Washer Dryer Combo", category: "Appliances", portal: "Appliance lab", image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=900", rating: 4.3, score: 8.6, reviews: 860, trend: "+7%", price: "$1,799", verdict: "Space-saving washer dryer for apartments and compact laundry rooms.", pros: ["One machine", "Smart cycles", "Space saving"], specs: { Display: "Control panel", Processor: "Smart laundry controls", Camera: "N/A", Battery: "N/A", Storage: "N/A", Warranty: "1 year" } },
  { id: "samsung-bespoke-fridge", name: "Samsung Bespoke Refrigerator", category: "Appliances", portal: "Kitchen review", image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=900", rating: 4.4, score: 8.8, reviews: 1044, trend: "+8%", price: "$2,199", verdict: "Customizable smart refrigerator with flexible storage.", pros: ["Flexible design", "Smart features", "Good capacity"], specs: { Display: "Optional smart display", Processor: "SmartThings controls", Camera: "N/A", Battery: "N/A", Storage: "Large capacity", Warranty: "1 year" } },
  { id: "instant-pot-duo", name: "Instant Pot Duo", category: "Appliances", portal: "Kitchen review", image: "https://images.unsplash.com/photo-1583241475880-083f84372725?w=900", rating: 4.6, score: 8.9, reviews: 9200, trend: "+6%", price: "$99", verdict: "Popular multi-cooker for fast meals, rice, soups, and pressure cooking.", pros: ["Versatile", "Affordable", "Easy meals"], specs: { Display: "Control panel", Processor: "Cooking program controls", Camera: "N/A", Battery: "N/A", Storage: "N/A", Warranty: "1 year" } },
  { id: "philips-air-fryer", name: "Philips Air Fryer XXL", category: "Appliances", portal: "Kitchen lab", image: "https://images.unsplash.com/photo-1583241475880-083f84372725?w=900", rating: 4.5, score: 8.8, reviews: 6811, trend: "+10%", price: "$249", verdict: "Large air fryer for crisp food with less oil.", pros: ["Large basket", "Crisp results", "Easy controls"], specs: { Display: "Digital controls", Processor: "Cooking presets", Camera: "N/A", Battery: "N/A", Storage: "N/A", Warranty: "1 year" } },
  { id: "ecovacs-deebot-x5", name: "Ecovacs Deebot X5", category: "Appliances", portal: "Robot vacuum lab", image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=900", rating: 4.3, score: 8.7, reviews: 731, trend: "+11%", price: "$899", verdict: "Robot vacuum and mop with smart mapping for busy homes.", pros: ["Auto mapping", "Mop support", "Good automation"], specs: { Display: "App controls", Processor: "Navigation sensors", Camera: "Mapping sensors", Battery: "Large rechargeable pack", Storage: "Dust bin", Warranty: "1 year" } }
);

reviewData.reviews.push(
  { productId: "iphone-15-pro-max", author: "Paolo M.", type: "Verified buyer", rating: 5, date: "2026-06-06T12:20:00+08:00", title: "Video quality is excellent", text: "The cameras are consistent and the phone feels fast even with heavy editing apps." },
  { productId: "oneplus-12", author: "Rhea L.", type: "Verified buyer", rating: 5, date: "2026-06-06T15:10:00+08:00", title: "Charging changed my routine", text: "The fast charging is the feature I notice every day. Performance is also very smooth." },
  { productId: "garmin-fenix-8", author: "Andre V.", type: "Verified buyer", rating: 5, date: "2026-06-05T07:45:00+08:00", title: "Best watch for long hikes", text: "Battery life and maps are the main reasons I bought it. It feels tough and accurate." },
  { productId: "lg-c4-oled-tv", author: "Sam K.", type: "Verified buyer", rating: 5, date: "2026-06-04T19:35:00+08:00", title: "Movies look incredible", text: "Black levels and gaming response are both excellent. Bright rooms still need curtains." },
  { productId: "instant-pot-duo", author: "Nina C.", type: "Verified buyer", rating: 4, date: "2026-06-03T18:05:00+08:00", title: "Very useful kitchen tool", text: "Great for rice, soups, and quick meals. The learning curve is small after a few uses." }
);

reviewData.externalReviews = {
  "iphone-15-pro-max": [
    { site: "PhoneArena", title: "iPhone 15 Pro Max review", url: "https://www.phonearena.com/reviews/iphone-15-pro-max-review_id5850" }
  ],
  "galaxy-s24-ultra": [
    { site: "TechRadar", title: "Samsung Galaxy S24 Ultra review", url: "https://www.techradar.com/phones/samsung-galaxy-phones/samsung-galaxy-s24-ultra-review" }
  ],
  "pixel-8-pro": [
    { site: "Android Authority", title: "Google Pixel 8 Pro review", url: "https://www.androidauthority.com/google-pixel-8-pro-review-3374117/" },
    { site: "Ars Technica", title: "Pixel 8 Pro review", url: "https://arstechnica.com/google/2023/10/pixel-8-pro-review-the-best-android-phone/" }
  ],
  "oneplus-12": [
    { site: "Android Central", title: "OnePlus 12 review", url: "https://www.androidcentral.com/phones/oneplus-12-review" },
    { site: "TechRadar", title: "OnePlus 12 review", url: "https://www.techradar.com/phones/android/oneplus-12-review" }
  ],
  "lg-c4-oled-tv": [
    { site: "RTINGS", title: "LG C4 OLED TV review", url: "https://www.rtings.com/tv/reviews/lg/c4-oled/" },
    { site: "Tom's Guide", title: "LG C4 OLED TV review", url: "https://www.tomsguide.com/tvs/lg-c4-oled-tv-review" }
  ],
  "garmin-fenix-8": [
    { site: "DC Rainmaker", title: "Garmin Fenix 8 in-depth review", url: "https://www.dcrainmaker.com/2024/08/garmin-fenix-8-in-depth-review.html/comment-page-1" }
  ],
  "ipad-pro-m4": [
    { site: "Tom's Guide", title: "iPad Pro M4 review", url: "https://www.tomsguide.com/tablets/ipads/ipad-pro-2024/" },
    { site: "PhoneArena", title: "iPad Pro M4 review", url: "https://www.phonearena.com/reviews/ipad-pro-2024-review_id6187" }
  ],
  "sony-wh-1000xm7": [
    { site: "RTINGS", title: "Sony WH-1000XM5 Wireless review", url: "https://www.rtings.com/headphones/reviews/sony/wh-1000xm5-wireless" },
    { site: "SoundGuys", title: "Sony WH-1000XM5 review", url: "https://www.soundguys.com/sony-wh-1000xm5-review-71783/" }
  ]
};

reviewData.recommendations = [
  { productId: "galaxy-s24-ultra", badge: "Best Android phone", reason: "Top-tier camera, stylus support, strong display, and long-term flagship value." },
  { productId: "iphone-15-pro-max", badge: "Best iPhone buy", reason: "Excellent video, premium build, and broad accessory/software support." },
  { productId: "oneplus-12", badge: "Best performance value", reason: "Flagship speed and fast charging at a lower price than many premium phones." },
  { productId: "garmin-fenix-8", badge: "Best fitness watch", reason: "Great battery life, outdoor features, maps, and serious training metrics." },
  { productId: "lg-c4-oled-tv", badge: "Best TV upgrade", reason: "Excellent OLED picture quality for movies and gaming." },
  { productId: "instant-pot-duo", badge: "Best kitchen value", reason: "Affordable, versatile, and useful for everyday cooking." }
];

reviewData.articles = [
  { id: "best-smartphones-2026", title: "Best Smartphones of 2026", category: "Smartphones", date: "2026-06-06T08:00:00+08:00", source: "ReviewHub Editorial", image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200", summary: "A practical ranking of phones for camera quality, battery life, gaming, software support, and value.", products: ["galaxy-s24-ultra", "iphone-15-pro-max", "oneplus-12"], takeaways: ["Choose Galaxy S24 Ultra for zoom and stylus work.", "Choose iPhone 15 Pro Max for video and iOS support.", "Choose OnePlus 12 for speed and charging value."], sections: [{ heading: "How to choose", body: "Start with software preference, then camera needs, battery life, and repair/support expectations. A flagship is not always the best buy if a midrange phone already handles your daily apps well." }, { heading: "What matters most", body: "Display brightness, update support, camera consistency, charging speed, and storage are the specs most users feel after the first week." }] },
  { id: "android-vs-iphone-buying-guide", title: "Android vs iPhone: Which Should You Buy?", category: "Smartphones", date: "2026-06-05T09:30:00+08:00", source: "ReviewHub Buying Guide", image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=1200", summary: "A direct guide to choosing between Android flexibility and iPhone ecosystem stability.", products: ["iphone-15", "iphone-15-pro-max", "galaxy-s24-ultra"], takeaways: ["iPhone is strongest for long support and video.", "Android is strongest for hardware variety and customization.", "Your existing laptop, watch, and cloud services should influence the decision."], sections: [{ heading: "Ecosystem", body: "Buy the phone that works best with your watch, earbuds, cloud photos, and laptop. Switching platforms can be worthwhile, but app purchases and accessories add hidden costs." }, { heading: "Value", body: "Android offers more price tiers. iPhone usually holds resale value well, which can reduce long-term ownership cost." }] },
  { id: "best-camera-phones", title: "Best Camera Phones for Photos and Video", category: "Smartphones", date: "2026-06-04T10:10:00+08:00", source: "Camera Desk", image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=1200", summary: "What to check before buying a phone mainly for photos, portraits, zoom, and video.", products: ["pixel-8-pro", "xiaomi-14-ultra", "iphone-15-pro-max"], takeaways: ["Pixel phones are strong for quick point-and-shoot photos.", "iPhone remains a strong video choice.", "Ultra camera phones are better when you actually use zoom lenses."], sections: [{ heading: "Photo quality", body: "Look for consistent color, fast shutter response, and reliable skin tones. Large megapixel numbers alone do not guarantee better photos." }, { heading: "Video quality", body: "Video depends on stabilization, audio capture, lens switching, and heat management as much as resolution." }] },
  { id: "best-budget-phones", title: "Best Budget and Midrange Phones", category: "Smartphones", date: "2026-06-03T14:00:00+08:00", source: "Value Lab", image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=1200", summary: "How to find a phone that feels fast without paying flagship prices.", products: ["galaxy-a55", "motorola-edge-50-pro", "nothing-phone-2"], takeaways: ["Prioritize display, battery, and update policy.", "Avoid very low storage if you keep videos offline.", "A midrange phone can be better value than an older flagship."], sections: [{ heading: "What to avoid", body: "Avoid weak storage, poor update promises, and phones with too little RAM for your daily apps." }, { heading: "Best value signs", body: "A bright OLED screen, large battery, and clean software usually matter more than a flagship-grade benchmark score." }] },
  { id: "phone-battery-guide", title: "Phone Battery and Charging Guide", category: "Smartphones", date: "2026-06-02T11:20:00+08:00", source: "Battery Desk", image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=1200", summary: "Battery size, charging speed, wireless charging, and real endurance explained clearly.", products: ["oneplus-12", "galaxy-s24-ultra", "pixel-8-pro"], takeaways: ["Battery capacity is only one part of endurance.", "Charging speed matters if you often forget overnight charging.", "Heat affects battery health over time."], sections: [{ heading: "Capacity versus endurance", body: "A 5,000mAh phone can still drain quickly if the display, modem, or processor is inefficient." }, { heading: "Charging", body: "Fast charging is convenient, but heat management and charger compatibility matter for long-term battery health." }] },
  { id: "best-laptops-students", title: "Best Laptops for Students", category: "Laptops", date: "2026-06-01T08:45:00+08:00", source: "Laptop Desk", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=1200", summary: "Portable laptops for classes, research, writing, video calls, and battery life.", products: ["macbook-air-m5", "dell-xps-14"], takeaways: ["Battery and keyboard quality matter every day.", "Start with 16GB memory if budget allows.", "A lighter laptop is easier to carry for years."], sections: [{ heading: "Student basics", body: "A good student laptop should be light, quiet, reliable, and comfortable to type on for long sessions." }, { heading: "Storage", body: "Cloud storage helps, but local storage still matters for videos, apps, and offline work." }] },
  { id: "gaming-laptop-guide", title: "Gaming Laptop Buying Guide", category: "Laptops", date: "2026-05-31T12:30:00+08:00", source: "Gaming Bench", image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=1200", summary: "How to compare GPU power, thermals, display refresh rate, and portability.", products: ["rog-zephyrus-g16"], takeaways: ["GPU wattage affects real performance.", "Cooling design matters more than thinness.", "OLED screens look excellent but can raise price."], sections: [{ heading: "Performance", body: "The same GPU name can perform differently depending on power limits and cooling." }, { heading: "Portability", body: "A thin gaming laptop is easier to carry, but often gets louder under load." }] },
  { id: "laptop-under-1000", title: "Best Laptops Under $1000", category: "Laptops", date: "2026-05-30T09:00:00+08:00", source: "ReviewHub Buying Guide", image: "https://images.unsplash.com/photo-1587554801471-37976a256db0?w=1200", summary: "Affordable laptop picks for students, office work, and hybrid productivity.", products: ["dell-xps-14", "macbook-air-m5"], takeaways: ["Look for a good display and keyboard first.", "Do not buy too little memory for long-term use.", "Refurbished premium laptops can be excellent value."], sections: [{ heading: "Core specs", body: "For most users, modern processors are fast enough. Memory, storage, screen quality, and battery life are more noticeable." }, { heading: "Build quality", body: "A stronger hinge, better keyboard, and lighter body can matter more than a small speed difference." }] },
  { id: "oled-tv-guide", title: "OLED TV Buying Guide", category: "Appliances", date: "2026-05-29T16:15:00+08:00", source: "TV Lab", image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=1200", summary: "OLED strengths, brightness limits, gaming features, and room setup explained.", products: ["lg-c4-oled-tv", "samsung-frame-tv"], takeaways: ["OLED is excellent for contrast and movies.", "Bright rooms may need a brighter LED/QLED model.", "Gamers should check HDMI 2.1 and refresh rate."], sections: [{ heading: "Picture quality", body: "OLED pixels turn off individually, producing excellent black levels and contrast." }, { heading: "Room lighting", body: "A bright living room can reduce perceived contrast, so room setup matters." }] },
  { id: "best-smartwatches", title: "Best Smartwatches and Fitness Watches", category: "Wearables", date: "2026-05-28T07:50:00+08:00", source: "Wearables Desk", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1200", summary: "Choose between smartwatch apps, health tracking, training metrics, and battery life.", products: ["garmin-fenix-8", "apple-watch-ultra-3", "samsung-galaxy-watch-9"], takeaways: ["Garmin is strongest for battery and training.", "Apple Watch is strongest for iPhone integration.", "Samsung watches are best for many Android users."], sections: [{ heading: "Platform", body: "Compatibility should be checked first. Some watches work best only with certain phones." }, { heading: "Health tracking", body: "Look for consistent tracking trends rather than treating every sensor reading as medical-grade data." }] },
  { id: "headphones-anc-guide", title: "Noise-Canceling Headphones Compared", category: "Audio", date: "2026-05-27T13:40:00+08:00", source: "Audio Lab Notes", image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200", summary: "ANC strength, comfort, microphones, app controls, and battery life compared.", products: ["sony-wh-1000xm7", "airpods-pro-3"], takeaways: ["Comfort matters as much as noise canceling.", "Travelers should check case size and battery.", "Microphone quality varies a lot in noisy places."], sections: [{ heading: "ANC", body: "The best ANC headphones reduce low-frequency noise well, but voices and sudden sounds are harder to remove." }, { heading: "Comfort", body: "Clamping force, ear pad material, and weight determine whether headphones are good for long sessions." }] },
  { id: "earbuds-vs-headphones", title: "Earbuds vs Headphones: Which Is Better?", category: "Audio", date: "2026-05-26T15:05:00+08:00", source: "Audio Desk", image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=1200", summary: "A simple guide to choosing portable earbuds or over-ear headphones.", products: ["airpods-pro-3", "sony-wh-1000xm7"], takeaways: ["Earbuds are better for commuting and workouts.", "Headphones usually win on comfort and battery.", "Call quality depends heavily on microphones and noise reduction."], sections: [{ heading: "Portability", body: "Earbuds fit in a pocket and are easier to carry daily." }, { heading: "Sound and comfort", body: "Over-ear headphones often provide a bigger sound and less ear fatigue during long use." }] },
  { id: "tablet-buying-guide", title: "Tablet Buying Guide", category: "Tablets", date: "2026-05-25T10:35:00+08:00", source: "Tablet Desk", image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=1200", summary: "How to choose a tablet for school, drawing, reading, streaming, and work.", products: ["ipad-pro-m4", "galaxy-tab-s9-ultra"], takeaways: ["Pick the app ecosystem first.", "Keyboard and stylus cost can change the real price.", "A laptop is still better for heavy desktop workflows."], sections: [{ heading: "Apps", body: "Creative and productivity apps can decide the platform more than hardware specs." }, { heading: "Accessories", body: "Add the cost of keyboard, stylus, case, and storage before comparing final value." }] },
  { id: "ereader-guide", title: "E-Reader Buying Guide", category: "Gadgets", date: "2026-05-24T08:25:00+08:00", source: "Reader Desk", image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200", summary: "What matters in an e-reader: screen size, lighting, waterproofing, storage, and ecosystem.", products: ["kindle-paperwhite"], takeaways: ["E-ink is easier on the eyes than tablets for long reading.", "Water resistance helps for travel and bedtime reading.", "Library and store support matter."], sections: [{ heading: "Screen", body: "A sharp e-ink display with adjustable light is the core feature." }, { heading: "Storage", body: "Books use little storage, but audiobooks can fill a device faster." }] },
  { id: "console-buying-guide", title: "Game Console Buying Guide", category: "Gaming", date: "2026-05-23T18:10:00+08:00", source: "Gaming Desk", image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=1200", summary: "How to choose between power, portability, exclusives, subscriptions, and family games.", products: ["sony-ps5-slim", "nintendo-switch-oled"], takeaways: ["PS5 is better for cinematic high-performance games.", "Switch OLED is better for portable and family gaming.", "Game library matters more than raw hardware."], sections: [{ heading: "Games first", body: "Pick the console that has the games you actually want to play." }, { heading: "Subscriptions", body: "Online play, free monthly games, and cloud saves can add recurring costs." }] },
  { id: "robot-vacuum-guide", title: "Robot Vacuum Buying Guide", category: "Appliances", date: "2026-05-22T11:45:00+08:00", source: "Home Lab", image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=1200", summary: "Mapping, suction, mopping, obstacle avoidance, and maintenance explained.", products: ["ecovacs-deebot-x5", "dyson-v16-detect"], takeaways: ["Mapping quality determines daily usefulness.", "Self-empty docks reduce maintenance.", "Pet hair needs strong brushes and easy cleaning."], sections: [{ heading: "Navigation", body: "A robot vacuum with accurate mapping cleans more efficiently and avoids repeated passes." }, { heading: "Maintenance", body: "Brushes, filters, mop pads, and bins still need regular attention." }] },
  { id: "vacuum-cleaner-guide", title: "Cordless Vacuum Buying Guide", category: "Appliances", date: "2026-05-21T09:15:00+08:00", source: "Home Appliance Lab", image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=1200", summary: "Suction, runtime, dust bins, filters, attachments, and pet hair performance.", products: ["dyson-v16-detect"], takeaways: ["Runtime claims depend on power mode.", "Attachments matter for stairs and furniture.", "A small bin is annoying in large homes."], sections: [{ heading: "Runtime", body: "High-power modes drain batteries quickly, so real runtime can be far lower than headline claims." }, { heading: "Filtration", body: "Good filters and sealed systems help keep dust from escaping back into the room." }] },
  { id: "air-fryer-guide", title: "Air Fryer Buying Guide", category: "Appliances", date: "2026-05-20T17:30:00+08:00", source: "Kitchen Lab", image: "https://images.unsplash.com/photo-1583241475880-083f84372725?w=1200", summary: "Basket size, controls, cleaning, and cooking performance for quick meals.", products: ["philips-air-fryer", "instant-pot-duo"], takeaways: ["Choose basket size based on household size.", "Removable parts make cleaning easier.", "Air fryers are great for crisping, not every kind of cooking."], sections: [{ heading: "Capacity", body: "Small baskets are fine for snacks, while families need larger models." }, { heading: "Cleaning", body: "Dishwasher-safe parts and nonstick baskets save time." }] },
  { id: "refrigerator-guide", title: "Smart Refrigerator Buying Guide", category: "Appliances", date: "2026-05-19T12:05:00+08:00", source: "Kitchen Desk", image: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=1200", summary: "Capacity, layout, smart features, energy use, and warranty considerations.", products: ["samsung-bespoke-fridge"], takeaways: ["Measure your kitchen before comparing features.", "Flexible shelves matter more than flashy screens.", "Energy efficiency affects long-term cost."], sections: [{ heading: "Fit", body: "Measure width, height, depth, door swing, and delivery path before buying." }, { heading: "Storage", body: "Flexible shelves and freezer layout affect daily convenience." }] },
  { id: "washer-dryer-guide", title: "Washer Dryer Combo Buying Guide", category: "Appliances", date: "2026-05-18T15:50:00+08:00", source: "Laundry Lab", image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=1200", summary: "Capacity, drying time, water use, smart cycles, and apartment fit.", products: ["lg-washer-dryer-combo"], takeaways: ["Combos save space but can take longer.", "Capacity matters for families.", "Check venting and water requirements."], sections: [{ heading: "Space", body: "A combo unit is useful when you cannot fit separate washer and dryer machines." }, { heading: "Cycle time", body: "Drying can take longer than a dedicated dryer, so plan around laundry volume." }] },
  { id: "smart-home-basics", title: "Smart Home Basics for Beginners", category: "Gadgets", date: "2026-05-17T10:00:00+08:00", source: "Smart Home Desk", image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=1200", summary: "Start with useful smart home upgrades without overcomplicating your setup.", products: ["samsung-bespoke-fridge", "ecovacs-deebot-x5"], takeaways: ["Start with lights, plugs, and cleaning automation.", "Avoid buying devices that need too many separate apps.", "Privacy settings deserve attention."], sections: [{ heading: "Start small", body: "A smart plug, robot vacuum, or smart display can be more useful than a large whole-home setup." }, { heading: "Compatibility", body: "Check whether devices support the same ecosystem before buying." }] },
  { id: "how-to-read-reviews", title: "How to Read Product Reviews Correctly", category: "Buying Tips", date: "2026-05-16T08:30:00+08:00", source: "ReviewHub Editorial", image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200", summary: "Learn how to spot useful reviews, biased reviews, and specs that matter.", products: ["iphone-15-pro-max", "lg-c4-oled-tv"], takeaways: ["Look for repeated long-term complaints.", "Separate reviewer preference from product weakness.", "Check both expert reviews and buyer reviews."], sections: [{ heading: "Patterns matter", body: "One angry review is less useful than a repeated issue across many users and sources." }, { heading: "Context", body: "A reviewer who values gaming may rank a product differently than someone who values battery or comfort." }] },
  { id: "specs-that-matter", title: "Specs That Actually Matter", category: "Buying Tips", date: "2026-05-15T13:25:00+08:00", source: "ReviewHub Lab", image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200", summary: "A simple explanation of specs that change real daily experience.", products: ["oneplus-12", "macbook-air-m5", "sony-wh-1000xm7"], takeaways: ["Screen, battery, storage, and support usually matter most.", "Benchmarks are useful but incomplete.", "Comfort and reliability are specs you feel daily."], sections: [{ heading: "Daily specs", body: "A bright screen, reliable battery, enough storage, and a good keyboard or grip affect daily use more than small benchmark gaps." }, { heading: "Support", body: "Software updates and warranty support can extend the useful life of a product." }] },
  { id: "best-products-for-travel", title: "Best Tech Products for Travel", category: "Buying Tips", date: "2026-05-14T07:40:00+08:00", source: "Travel Kit Desk", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200", summary: "Travel-friendly phones, headphones, readers, tablets, watches, and compact chargers.", products: ["sony-wh-1000xm7", "kindle-paperwhite", "garmin-fenix-8"], takeaways: ["Noise canceling is worth it for flights.", "E-readers beat tablets for long reading.", "Battery life matters more when outlets are limited."], sections: [{ heading: "Pack light", body: "Choose devices that serve multiple purposes and charge by USB-C when possible." }, { heading: "Durability", body: "Water resistance and strong cases matter more when you travel often." }] },
  { id: "recommended-buys-2026", title: "ReviewHub Recommended Buys for 2026", category: "Buying Tips", date: "2026-05-13T09:55:00+08:00", source: "ReviewHub Editorial", image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200", summary: "The products we would shortlist first across phones, laptops, wearables, TV, and kitchen gear.", products: ["galaxy-s24-ultra", "oneplus-12", "garmin-fenix-8", "lg-c4-oled-tv"], takeaways: ["Buy based on your workflow, not hype.", "High score plus high review volume is a strong signal.", "The best buy is the one you will use fully."], sections: [{ heading: "Our method", body: "We prioritize rating, score, review volume, current trend, and practical ownership value." }, { heading: "Shortlist", body: "Start with the recommended cards, then compare products by category before buying." }] }
];
